/* eslint-disable */
// Generated by Wrangler by running `wrangler types workers/fulfillment/worker-configuration.d.ts --config workers/fulfillment/wrangler.toml --env staging --env-interface FulfillmentEnv --include-runtime=false` (hash: 0386f7d6ae54d0d5a8ea3d484e4e7b27)
interface __BaseEnv_FulfillmentEnv {
	FULFILLMENT_QUEUE: Queue;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	NODE_ENV: "production";
	PUBLIC_APP_ENV: "staging";
	SUPABASE_EXPECTED_PROJECT_REF: "mzjyvmlxfpzdfdjzxxyj";
	WORKER_IDENTITY: "espanol-honesto-fulfillment-staging";
	PUBLIC_SITE_URL: "https://espanolhonesto-staging.alindev95.workers.dev";
	CHECKOUT_ENABLED: "false";
	CHECKOUT_ENABLED_OVERRIDE: "false";
	FULFILLMENT_RUNTIME_MODE: "active";
	EMAIL_DELIVERY_MODE: "allowlist";
	EMAIL_DAILY_RECIPIENT_LIMIT: "10";
	EMAIL_MONTHLY_RECIPIENT_LIMIT: "100";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_FulfillmentEnv {}
}
interface FulfillmentEnv extends __BaseEnv_FulfillmentEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NODE_ENV" | "PUBLIC_APP_ENV" | "SUPABASE_EXPECTED_PROJECT_REF" | "WORKER_IDENTITY" | "PUBLIC_SITE_URL" | "CHECKOUT_ENABLED" | "CHECKOUT_ENABLED_OVERRIDE" | "FULFILLMENT_RUNTIME_MODE" | "EMAIL_DELIVERY_MODE" | "EMAIL_DAILY_RECIPIENT_LIMIT" | "EMAIL_MONTHLY_RECIPIENT_LIMIT">> {}
}
