/**
 * Email Module - Main exports
 */
export {
    deliverEmail,
    deliverIdempotentEmail,
    getEmailDeliveryPolicy,
    normalizeEmailAddressForDelivery,
    PRODUCTION_EMAIL_DAILY_RECIPIENT_LIMIT,
    PRODUCTION_EMAIL_MONTHLY_RECIPIENT_LIMIT,
    STAGING_EMAIL_DAILY_RECIPIENT_LIMIT,
    STAGING_EMAIL_MONTHLY_RECIPIENT_LIMIT,
    type BudgetedEmail,
    type EmailDeliveryFailureReason,
    type EmailDeliveryMode,
    type EmailDeliveryPolicy,
    type EmailDeliveryResult,
    type IdempotentBudgetedEmail,
    type IdempotentEmailDeliveryResult,
} from './delivery';

export {
    baseTemplate,
    welcomeEmailTemplate,
    renewalNoticeEmailTemplate,
    renewalNoticeSubject,
    guaranteeRefundEmailTemplate,
    guaranteeRefundSubject,
    classConfirmationTemplate,
    classRescheduledTemplate,
    classRescheduledSubject,
    checkoutV2CycleRescheduledTemplate,
    checkoutV2CycleRescheduledSubject,
    classReminderTemplate,
    classCancelledTemplate,
    leadWelcomeTemplate,
    levelCheckInviteTemplate,
    missingInfoEmailTemplate,
    proposalNextStepEmailTemplate,
    supportTicketReceivedTemplate,
    supportTicketUpdatedTemplate,
    type WelcomeEmailData,
    type RenewalNoticeEmailData,
    type RenewalNoticeLocale,
    type GuaranteeRefundEmailData,
    type GuaranteeRefundLocale,
    type ClassConfirmationData,
    type ClassRescheduledData,
    type CheckoutV2CycleRescheduledData,
    type ClassReminderData,
    type ClassCancelledData,
    type LeadWelcomeEmailData,
    type LevelCheckInviteEmailData,
    type MissingInfoEmailData,
    type ProposalNextStepEmailData,
    type SupportTicketReceivedEmailData,
    type SupportTicketUpdatedEmailData,
} from './templates';

export {
    sendWelcomeEmail,
    sendRenewalNoticeEmail,
    sendGuaranteeRefundEmail,
    sendClassConfirmation,
    sendClassRescheduled,
    sendCheckoutV2CycleRescheduled,
    sendClassReminder,
    sendClassCancelled,
    sendClassConfirmationToBoth,
    sendClassCancelledToBoth,
    sendLeadWelcomeEmail,
    sendLevelCheckInviteEmail,
    sendMissingInfoEmail,
    sendProposalNextStepEmail,
    sendSupportTicketReceivedEmail,
    sendSupportTicketUpdatedEmail,
    type TransactionalEmailSendOptions,
} from './send';
